#jeg vil ikke ha hjelp fra pus
name: soknad-kontantstotte-api
image: repo.adeo.no:5443/soknad/soknad-kontantstotte-api
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    initialDelay: 60
    path: /api/status/isAlive
  readiness:
    initialDelay: 60
    path: /api/status/isAlive
ingress:
  enabled: true
fasitResources:
  used:
  - alias: aad_b2c_clientid
    resourceType: credential
    propertyMap:
      username: NO_NAV_SECURITY_OIDC_ISSUER_SELVBETJENING_ACCEPTEDAUDIENCE
  - alias: aad_b2c_discovery
    resourceType: baseurl
    propertyMap:
      url: NO_NAV_SECURITY_OIDC_ISSUER_SELVBETJENING_DISCOVERYURL
  - alias: appres.cms
    resourceType: baseUrl
  - alias: soknad-kontantstotte-proxy-api
    resourceType: restservice
  - alias: soknad-pdf-generator
    resourceType: restservice
  - alias: soknad-kontantstotte-api-soknad-kontantstotte-proxy-api-apiKey
    resourceType: credential