server:
  servlet:
    context-path: /soknad-kontantstotte-api

spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
management:
   endpoints.web.exposure.include:  '*'