no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
     discoveryurl: http://metadata
     accepted_audience: aud-localhost
     cookie_name: localhost-idtoken

UNLEASH_API_URL: http://localhost
APP_NAME: soknad-kontantstotte-api

SOKNAD_PDF_SVG_SUPPORT_GENERATOR_URL: http://localhost:8082/api
SOKNAD_HTML_GENERATOR_URL: http://localhost:9000/api

TPS-PROXY_API_V1_INNSYN_URL: http://dummyTps/api

SOKNAD_KONTANTSTOTTE_API_SOKNAD_KONTANTSTOTTE_PROXY_API_APIKEY_USERNAME: anything
SOKNAD_KONTANTSTOTTE_API_SOKNAD_KONTANTSTOTTE_PROXY_API_APIKEY_PASSWORD: anything
SOKNAD-KONTANTSTOTTE-API-TPS-PROXY_API_V1_INNSYN-APIKEY_USERNAME: anything
SOKNAD-KONTANTSTOTTE-API-TPS-PROXY_API_V1_INNSYN-APIKEY_PASSWORD: anything

logging:
  level:
    org.springframework: INFO
    org.glassfish.jersey: WARN
    org.glassfish.jersey.logging.LoggingFeature: DEBUG
    com.fasterxml: WARN
  config: classpath:logback-spring-test.xml